const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, '..', '..', '.env') });
const { Pool } = require('pg');

const perguntas = [
  // Conhecimentos Gerais (30)
  { categoria: 'Conhecimentos Gerais', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a capital do Brasil?', resposta_correta: 'Brasília', respostas_incorretas: ['Rio de Janeiro', 'São Paulo', 'Salvador'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o maior planeta do Sistema Solar?', resposta_correta: 'Júpiter', respostas_incorretas: ['Saturno', 'Terra', 'Marte'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é a moeda oficial do Japão?', resposta_correta: 'Iene', respostas_incorretas: ['Won', 'Yuan', 'Dólar'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o maior oceano do planeta?', resposta_correta: 'Pacífico', respostas_incorretas: ['Atlântico', 'Índico', 'Ártico'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quantos continentes existem?', resposta_correta: '7', respostas_incorretas: ['5', '6', '8'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o idioma oficial do Brasil?', resposta_correta: 'Português', respostas_incorretas: ['Espanhol', 'Inglês', 'Francês'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a fórmula química da água?', resposta_correta: 'H2O', respostas_incorretas: ['CO2', 'O2', 'NaCl'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é a menor unidade da matéria?', resposta_correta: 'Átomo', respostas_incorretas: ['Célula', 'Molécula', 'Planeta'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual animal é conhecido como o rei da selva?', resposta_correta: 'Leão', respostas_incorretas: ['Tigre', 'Elefante', 'Leopardo'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quantos lados tem um hexágono?', resposta_correta: '6', respostas_incorretas: ['5', '7', '8'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual instrumento mede a temperatura?', resposta_correta: 'Termômetro', respostas_incorretas: ['Barômetro', 'Higrômetro', 'Anemômetro'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual cor resulta da mistura de azul e amarelo?', resposta_correta: 'Verde', respostas_incorretas: ['Roxo', 'Laranja', 'Marrom'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'medio', pontuacao: 20, pergunta: 'Em que data ocorreu a Independência do Brasil?', resposta_correta: '7 de setembro de 1822', respostas_incorretas: ['15 de novembro de 1889', '21 de abril de 1792', '1 de janeiro de 1500'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o planeta conhecido como planeta vermelho?', resposta_correta: 'Marte', respostas_incorretas: ['Vênus', 'Mercúrio', 'Júpiter'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a estrela mais próxima da Terra?', resposta_correta: 'Sol', respostas_incorretas: ['Sirius', 'Alpha Centauri', 'Vega'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o maior país da América do Sul?', resposta_correta: 'Brasil', respostas_incorretas: ['Argentina', 'Colômbia', 'Peru'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é o símbolo químico do ouro?', resposta_correta: 'Au', respostas_incorretas: ['Ag', 'Fe', 'Pb'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quantos dias tem um ano bissexto?', resposta_correta: '366', respostas_incorretas: ['365', '364', '360'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a maior floresta tropical do mundo?', resposta_correta: 'Amazônia', respostas_incorretas: ['Congo', 'Boreal', 'Tundra'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é o animal mais rápido em terra?', resposta_correta: 'Guepardo', respostas_incorretas: ['Leopardo', 'Tigre', 'Cavalo'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é o maior osso do corpo humano?', resposta_correta: 'Fêmur', respostas_incorretas: ['Tíbia', 'Úmero', 'Fíbula'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'medio', pontuacao: 20, pergunta: 'Quem pintou a Mona Lisa?', resposta_correta: 'Leonardo da Vinci', respostas_incorretas: ['Michelangelo', 'Rafael', 'Van Gogh'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual continente tem mais países?', resposta_correta: 'África', respostas_incorretas: ['Europa', 'Ásia', 'América'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o maior deserto quente do mundo?', resposta_correta: 'Saara', respostas_incorretas: ['Gobi', 'Atacama', 'Kalahari'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual país tem o mandarim como idioma oficial?', resposta_correta: 'China', respostas_incorretas: ['Japão', 'Coreia do Sul', 'Vietnã'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a capital de Portugal?', resposta_correta: 'Lisboa', respostas_incorretas: ['Porto', 'Braga', 'Coimbra'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é a unidade básica de armazenamento digital?', resposta_correta: 'Byte', respostas_incorretas: ['Bit', 'KB', 'GB'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual metal é líquido à temperatura ambiente?', resposta_correta: 'Mercúrio', respostas_incorretas: ['Ferro', 'Alumínio', 'Cobre'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quantas cores há no arco-íris?', resposta_correta: '7', respostas_incorretas: ['6', '5', '8'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a capital da Itália?', resposta_correta: 'Roma', respostas_incorretas: ['Milão', 'Veneza', 'Nápoles'] },

  // Perguntas adicionais de Conhecimentos Gerais - Difícil
  { categoria: 'Conhecimentos Gerais', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o elemento químico mais abundante no universo?', resposta_correta: 'Hidrogênio', respostas_incorretas: ['Hélio', 'Oxigênio', 'Carbono'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é a velocidade da luz no vácuo?', resposta_correta: '299.792.458 m/s', respostas_incorretas: ['300.000.000 m/s', '299.000.000 m/s', '298.000.000 m/s'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é a partícula subatômica com carga positiva?', resposta_correta: 'Próton', respostas_incorretas: ['Elétron', 'Nêutron', 'Fóton'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o nome da teoria que explica a origem do universo?', resposta_correta: 'Big Bang', respostas_incorretas: ['Teoria da Relatividade', 'Teoria Quântica', 'Teoria das Cordas'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o maior órgão interno do corpo humano?', resposta_correta: 'Fígado', respostas_incorretas: ['Pulmão', 'Coração', 'Cérebro'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é a unidade de medida da resistência elétrica?', resposta_correta: 'Ohm', respostas_incorretas: ['Volt', 'Ampere', 'Watt'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o nome do processo de divisão celular?', resposta_correta: 'Mitose', respostas_incorretas: ['Meiose', 'Osmose', 'Difusão'] },
  { categoria: 'Conhecimentos Gerais', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é a camada da atmosfera onde ocorrem os fenômenos meteorológicos?', resposta_correta: 'Troposfera', respostas_incorretas: ['Estratosfera', 'Mesosfera', 'Termosfera'] },

  // Futebol (30)
  { categoria: 'Futebol', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quantos jogadores cada time tem em campo no futebol?', resposta_correta: '11', respostas_incorretas: ['10', '12', '9'] },
  { categoria: 'Futebol', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a duração oficial de uma partida de futebol?', resposta_correta: '90 minutos', respostas_incorretas: ['60 minutos', '80 minutos', '100 minutos'] },
  { categoria: 'Futebol', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a competição mundial de seleções de futebol?', resposta_correta: 'Copa do Mundo', respostas_incorretas: ['Libertadores', 'Champions League', 'Copa América'] },
  { categoria: 'Futebol', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual país é o maior campeão da Copa do Mundo?', resposta_correta: 'Brasil', respostas_incorretas: ['Alemanha', 'Itália', 'Argentina'] },
  { categoria: 'Futebol', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a posição do jogador que defende o gol?', resposta_correta: 'Goleiro', respostas_incorretas: ['Zagueiro', 'Meio-campo', 'Atacante'] },
  { categoria: 'Futebol', dificuldade: 'facil', pontuacao: 10, pergunta: 'O cartão amarelo no futebol significa:', resposta_correta: 'Advertência', respostas_incorretas: ['Expulsão', 'Gol confirmado', 'Substituição'] },
  { categoria: 'Futebol', dificuldade: 'facil', pontuacao: 10, pergunta: 'O cartão vermelho no futebol significa:', resposta_correta: 'Expulsão', respostas_incorretas: ['Advertência', 'Pênalti', 'Substituição'] },
  { categoria: 'Futebol', dificuldade: 'facil', pontuacao: 10, pergunta: 'Como se chama a cobrança após uma falta?', resposta_correta: 'Cobrança de falta', respostas_incorretas: ['Escanteio', 'Lateral', 'Tiro de meta'] },
  { categoria: 'Futebol', dificuldade: 'facil', pontuacao: 10, pergunta: 'Como se chama a cobrança a partir da marca do pênalti?', resposta_correta: 'Pênalti', respostas_incorretas: ['Escanteio', 'Lateral', 'Tiro de meta'] },
  { categoria: 'Futebol', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é o principal torneio continental de clubes da América do Sul?', resposta_correta: 'Copa Libertadores', respostas_incorretas: ['Copa Sul-Americana', 'Champions League', 'Copa do Mundo'] },
  { categoria: 'Futebol', dificuldade: 'facil', pontuacao: 10, pergunta: 'O campo de futebol é dividido em quantas metades?', resposta_correta: '2', respostas_incorretas: ['3', '4', '1'] },
  { categoria: 'Futebol', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogador pode usar as mãos durante o jogo?', resposta_correta: 'Goleiro', respostas_incorretas: ['Atacante', 'Zagueiro', 'Meio-campo'] },
  { categoria: 'Futebol', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quem é conhecido como o Rei do Futebol?', resposta_correta: 'Pelé', respostas_incorretas: ['Maradona', 'Messi', 'Cristiano Ronaldo'] },
  { categoria: 'Futebol', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual seleção venceu a Copa do Mundo de 2002?', resposta_correta: 'Brasil', respostas_incorretas: ['Alemanha', 'França', 'Argentina'] },
  { categoria: 'Futebol', dificuldade: 'facil', pontuacao: 10, pergunta: 'Como se chama a reposição de bola feita com as mãos na lateral?', resposta_correta: 'Arremesso lateral', respostas_incorretas: ['Tiro de meta', 'Escanteio', 'Bola ao chão'] },
  { categoria: 'Futebol', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual seleção venceu a Copa do Mundo de 2014?', resposta_correta: 'Alemanha', respostas_incorretas: ['Brasil', 'Argentina', 'Espanha'] },
  { categoria: 'Futebol', dificuldade: 'facil', pontuacao: 10, pergunta: 'Em que país ocorreu a Copa do Mundo de 2014?', resposta_correta: 'Brasil', respostas_incorretas: ['África do Sul', 'Alemanha', 'Rússia'] },
  { categoria: 'Futebol', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual seleção venceu a Copa do Mundo de 2018?', resposta_correta: 'França', respostas_incorretas: ['Croácia', 'Alemanha', 'Brasil'] },
  { categoria: 'Futebol', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é a entidade máxima do futebol mundial?', resposta_correta: 'FIFA', respostas_incorretas: ['UEFA', 'CONMEBOL', 'CBF'] },
  { categoria: 'Futebol', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual torneio é o principal de clubes da Europa?', resposta_correta: 'Champions League', respostas_incorretas: ['Europa League', 'Copa UEFA', 'Supercopa'] },
  { categoria: 'Futebol', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual clube é o maior campeão da Champions League?', resposta_correta: 'Real Madrid', respostas_incorretas: ['Barcelona', 'Milan', 'Liverpool'] },
  { categoria: 'Futebol', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual cidade brasileira tem o estádio Maracanã?', resposta_correta: 'Rio de Janeiro', respostas_incorretas: ['São Paulo', 'Belo Horizonte', 'Salvador'] },
  { categoria: 'Futebol', dificuldade: 'medio', pontuacao: 20, pergunta: 'Como se chama a regra que impede o atacante de ficar à frente do último defensor?', resposta_correta: 'Impedimento', respostas_incorretas: ['Lateral', 'Escanteio', 'Falta'] },
  { categoria: 'Futebol', dificuldade: 'facil', pontuacao: 10, pergunta: 'Como se chama a disputa de pênaltis após empate?', resposta_correta: 'Disputa de pênaltis', respostas_incorretas: ['Prorrogação', 'Gol de ouro', 'Repescagem'] },
  { categoria: 'Futebol', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual posição atua nas laterais da defesa?', resposta_correta: 'Lateral', respostas_incorretas: ['Goleiro', 'Centroavante', 'Meia'] },
  { categoria: 'Futebol', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a forma de uma bola de futebol?', resposta_correta: 'Esférica', respostas_incorretas: ['Oval', 'Cúbica', 'Cilíndrica'] },
  { categoria: 'Futebol', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quantos títulos de Copa do Mundo a seleção do Brasil possui?', resposta_correta: '5', respostas_incorretas: ['4', '6', '3'] },
  { categoria: 'Futebol', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual seleção venceu a Copa do Mundo de 2010?', resposta_correta: 'Espanha', respostas_incorretas: ['Holanda', 'Alemanha', 'Brasil'] },
  { categoria: 'Futebol', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual seleção venceu a Copa do Mundo de 2006?', resposta_correta: 'Itália', respostas_incorretas: ['França', 'Alemanha', 'Brasil'] },
  { categoria: 'Futebol', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o principal campeonato nacional do Brasil?', resposta_correta: 'Brasileirão', respostas_incorretas: ['Copa do Brasil', 'Carioca', 'Paulista'] },

  // Perguntas adicionais de Futebol - Difícil
  { categoria: 'Futebol', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual jogador tem mais gols em Copas do Mundo?', resposta_correta: 'Miroslav Klose', respostas_incorretas: ['Pelé', 'Ronaldo', 'Gerd Müller'] },
  { categoria: 'Futebol', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Em que ano foi criada a FIFA?', resposta_correta: '1904', respostas_incorretas: ['1900', '1908', '1912'] },
  { categoria: 'Futebol', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual país sediou a primeira Copa do Mundo?', resposta_correta: 'Uruguai', respostas_incorretas: ['Brasil', 'Argentina', 'Itália'] },
  { categoria: 'Futebol', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o recorde de gols em uma única edição de Copa do Mundo?', resposta_correta: '13 gols (Just Fontaine)', respostas_incorretas: ['12 gols', '14 gols', '11 gols'] },
  { categoria: 'Futebol', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual clube tem mais títulos da Copa Libertadores?', resposta_correta: 'Independiente', respostas_incorretas: ['Boca Juniors', 'Peñarol', 'Estudiantes'] },
  { categoria: 'Futebol', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual jogador brasileiro nunca ganhou uma Bola de Ouro?', resposta_correta: 'Zico', respostas_incorretas: ['Ronaldinho', 'Kaká', 'Rivaldo'] },
  { categoria: 'Futebol', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Em que ano o Brasil perdeu a Copa do Mundo em casa?', resposta_correta: '1950', respostas_incorretas: ['1954', '2014', '1982'] },
  { categoria: 'Futebol', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o maior artilheiro da história do futebol?', resposta_correta: 'Pelé', respostas_incorretas: ['Cristiano Ronaldo', 'Messi', 'Romario'] },
  { categoria: 'Futebol', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual seleção tem mais participações em Copas do Mundo?', resposta_correta: 'Brasil', respostas_incorretas: ['Alemanha', 'Itália', 'Argentina'] },

  // Filmes (30)
  { categoria: 'Filmes', dificuldade: 'medio', pontuacao: 20, pergunta: 'Quem dirigiu o filme Titanic?', resposta_correta: 'James Cameron', respostas_incorretas: ['Steven Spielberg', 'Christopher Nolan', 'George Lucas'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual personagem é o portador do anel em O Senhor dos Anéis?', resposta_correta: 'Frodo Bolseiro', respostas_incorretas: ['Aragorn', 'Gandalf', 'Legolas'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual animação tem brinquedos que ganham vida?', resposta_correta: 'Toy Story', respostas_incorretas: ['Carros', 'Frozen', 'A Pequena Sereia'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Em Star Wars, quem é o pai de Luke Skywalker?', resposta_correta: 'Darth Vader', respostas_incorretas: ['Obi-Wan Kenobi', 'Yoda', 'Han Solo'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual filme tem o ogro verde chamado Shrek?', resposta_correta: 'Shrek', respostas_incorretas: ['Monstros S.A.', 'Madagascar', 'Kung Fu Panda'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual franquia acompanha o bruxo Harry Potter?', resposta_correta: 'Harry Potter', respostas_incorretas: ['Crepúsculo', 'Jogos Vorazes', 'Divergente'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual filme reúne vários heróis da Marvel em equipe?', resposta_correta: 'Os Vingadores', respostas_incorretas: ['X-Men', 'Quarteto Fantástico', 'Guardiões da Galáxia'] },
  { categoria: 'Filmes', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual filme fala sobre sonhos dentro de sonhos?', resposta_correta: 'A Origem', respostas_incorretas: ['Interestelar', 'Matrix', 'Clube da Luta'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quem é o protagonista do filme Matrix?', resposta_correta: 'Neo', respostas_incorretas: ['Morpheus', 'Smith', 'Trinity'] },
  { categoria: 'Filmes', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual filme de 1993 popularizou dinossauros em CGI?', resposta_correta: 'Jurassic Park', respostas_incorretas: ['King Kong', 'Godzilla', 'Tubarão'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual estúdio produziu Procurando Nemo?', resposta_correta: 'Pixar', respostas_incorretas: ['DreamWorks', 'Illumination', 'Ghibli'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual filme tem a frase "Que a Força esteja com você"?', resposta_correta: 'Star Wars', respostas_incorretas: ['Star Trek', 'Avatar', 'Duna'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Em qual filme aparece o personagem Jack Sparrow?', resposta_correta: 'Piratas do Caribe', respostas_incorretas: ['Indiana Jones', 'O Senhor dos Anéis', 'Harry Potter'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual filme da Disney tem o leão Simba?', resposta_correta: 'O Rei Leão', respostas_incorretas: ['Bambi', 'Tarzan', 'Mogli'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual filme da Disney tem a princesa Elsa?', resposta_correta: 'Frozen', respostas_incorretas: ['Moana', 'Mulan', 'A Bela e a Fera'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual filme tem o personagem James Bond?', resposta_correta: '007', respostas_incorretas: ['Missão Impossível', 'Bourne', 'Kingsman'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual filme tem o robô WALL-E?', resposta_correta: 'WALL-E', respostas_incorretas: ['Robôs', 'Big Hero 6', 'Toy Story'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual filme tem um parque com dinossauros vivos?', resposta_correta: 'Jurassic Park', respostas_incorretas: ['Godzilla', 'King Kong', 'Avatar'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual filme se passa no navio do amor e desastre de 1912?', resposta_correta: 'Titanic', respostas_incorretas: ['Pearl Harbor', 'Poseidon', 'O Aviador'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual filme mostra um ogro verde com um burro falante?', resposta_correta: 'Shrek', respostas_incorretas: ['Madagascar', 'Kung Fu Panda', 'Monstros S.A.'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual filme de animação se passa no fundo do mar com um peixe-palhaço?', resposta_correta: 'Procurando Nemo', respostas_incorretas: ['A Pequena Sereia', 'Moana', 'Luca'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual filme tem o herói Homem-Aranha?', resposta_correta: 'Homem-Aranha', respostas_incorretas: ['Batman', 'Superman', 'Lanterna Verde'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual filme é conhecido pela frase "Eu sou seu pai"?', resposta_correta: 'Star Wars', respostas_incorretas: ['Matrix', 'Vingadores', 'Batman'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual filme tem o personagem Woody e Buzz Lightyear?', resposta_correta: 'Toy Story', respostas_incorretas: ['Carros', 'Monstros S.A.', 'Up'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual filme tem o personagem Jack no navio afundando?', resposta_correta: 'Titanic', respostas_incorretas: ['Capitão Phillips', 'A Vida de Pi', 'O Resgate do Soldado Ryan'] },
  { categoria: 'Filmes', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual filme traz a cidade de Pandora?', resposta_correta: 'Avatar', respostas_incorretas: ['Duna', 'Interestelar', 'Star Trek'] },
  { categoria: 'Filmes', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual filme tem um robô terminador chamado T-800?', resposta_correta: 'O Exterminador do Futuro', respostas_incorretas: ['Robocop', 'Matrix', 'Blade Runner'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual filme tem o personagem Indiana Jones?', resposta_correta: 'Indiana Jones', respostas_incorretas: ['Missão Impossível', 'Rocky', 'Rambo'] },
  { categoria: 'Filmes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual filme é sobre carros falantes da Pixar?', resposta_correta: 'Carros', respostas_incorretas: ['Aviões', 'Toy Story', 'Up'] },
  { categoria: 'Filmes', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual filme apresenta o personagem Jack Skellington?', resposta_correta: 'O Estranho Mundo de Jack', respostas_incorretas: ['Coraline', 'A Noiva Cadáver', 'Frankenweenie'] },

  // Perguntas adicionais de Filmes - Médio
  { categoria: 'Filmes', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual filme de Christopher Nolan se passa em sonhos?', resposta_correta: 'A Origem', respostas_incorretas: ['Interestelar', 'Dunkirk', 'Tenet'] },
  { categoria: 'Filmes', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual ator interpretou o Coringa no filme Batman de 1989?', resposta_correta: 'Jack Nicholson', respostas_incorretas: ['Heath Ledger', 'Joaquin Phoenix', 'Jared Leto'] },
  { categoria: 'Filmes', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual filme ganhou o Oscar de Melhor Filme em 2020?', resposta_correta: 'Parasita', respostas_incorretas: ['1917', 'Era Uma Vez em Hollywood', 'Coringa'] },
  { categoria: 'Filmes', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual diretor fez a trilogia O Senhor dos Anéis?', resposta_correta: 'Peter Jackson', respostas_incorretas: ['Ridley Scott', 'George Lucas', 'Steven Spielberg'] },
  { categoria: 'Filmes', dificuldade: 'medio', pontuacao: 20, pergunta: 'Em que ano foi lançado o primeiro filme de Star Wars?', resposta_correta: '1977', respostas_incorretas: ['1975', '1979', '1980'] },
  { categoria: 'Filmes', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual atriz interpretou Katniss Everdeen em Jogos Vorazes?', resposta_correta: 'Jennifer Lawrence', respostas_incorretas: ['Emma Stone', 'Scarlett Johansson', 'Anne Hathaway'] },

  // Perguntas adicionais de Filmes - Difícil
  { categoria: 'Filmes', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual filme de Stanley Kubrick se passa em um hotel isolado?', resposta_correta: 'O Iluminado', respostas_incorretas: ['Laranja Mecânica', '2001: Uma Odisseia no Espaço', 'De Olhos Bem Fechados'] },
  { categoria: 'Filmes', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual filme de Akira Kurosawa inspirou Star Wars?', resposta_correta: 'A Fortaleza Escondida', respostas_incorretas: ['Os Sete Samurais', 'Yojimbo', 'Rashomon'] },
  { categoria: 'Filmes', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual ator interpretou Travis Bickle em Taxi Driver?', resposta_correta: 'Robert De Niro', respostas_incorretas: ['Al Pacino', 'Jack Nicholson', 'Dustin Hoffman'] },
  { categoria: 'Filmes', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual filme de Orson Welles é considerado um dos melhores de todos os tempos?', resposta_correta: 'Cidadão Kane', respostas_incorretas: ['A Marca da Maldade', 'O Terceiro Homem', 'A Dama de Shanghai'] },
  { categoria: 'Filmes', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual diretor fez Pulp Fiction?', resposta_correta: 'Quentin Tarantino', respostas_incorretas: ['Martin Scorsese', 'David Lynch', 'Coen Brothers'] },
  { categoria: 'Filmes', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual filme de Alfred Hitchcock tem a famosa cena do chuveiro?', resposta_correta: 'Psicose', respostas_incorretas: ['Vertigo', 'Os Pássaros', 'Janela Indiscreta'] },
  { categoria: 'Filmes', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual atriz ganhou o Oscar por Cisne Negro?', resposta_correta: 'Natalie Portman', respostas_incorretas: ['Mila Kunis', 'Winona Ryder', 'Barbara Hershey'] },
  { categoria: 'Filmes', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual filme de Francis Ford Coppola retrata a Guerra do Vietnã?', resposta_correta: 'Apocalipse Now', respostas_incorretas: ['Platoon', 'Nascido para Matar', 'Bom Dia, Vietnã'] },

  // Séries (30)
  { categoria: 'Séries', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é o nome do café em Friends?', resposta_correta: 'Central Perk', respostas_incorretas: ['Central Park', 'Coffee House', 'Perk Cafe'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quantos amigos principais há em Friends?', resposta_correta: '6', respostas_incorretas: ['5', '4', '7'] },
  { categoria: 'Séries', dificuldade: 'medio', pontuacao: 20, pergunta: 'Em Game of Thrones, qual é o continente principal?', resposta_correta: 'Westeros', respostas_incorretas: ['Essos', 'Narnia', 'Midgard'] },
  { categoria: 'Séries', dificuldade: 'medio', pontuacao: 20, pergunta: 'Em Game of Thrones, Jon Snow é da casa:', resposta_correta: 'Stark', respostas_incorretas: ['Lannister', 'Targaryen', 'Tyrell'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o nome do protagonista de Breaking Bad?', resposta_correta: 'Walter White', respostas_incorretas: ['Jesse Pinkman', 'Saul Goodman', 'Gus Fring'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a profissão de Walter White no início de Breaking Bad?', resposta_correta: 'Professor de química', respostas_incorretas: ['Policial', 'Médico', 'Advogado'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Em Stranger Things, qual é a cidade onde se passa a série?', resposta_correta: 'Hawkins', respostas_incorretas: ['Riverdale', 'Sunnydale', 'Hill Valley'] },
  { categoria: 'Séries', dificuldade: 'medio', pontuacao: 20, pergunta: 'Em The Office (US), a empresa se chama:', resposta_correta: 'Dunder Mifflin', respostas_incorretas: ['Paper & Co', 'Wernham Hogg', 'Scranton Paper'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Em The Office (US), a cidade é:', resposta_correta: 'Scranton', respostas_incorretas: ['Nova York', 'Boston', 'Chicago'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Em La Casa de Papel, o líder é conhecido como:', resposta_correta: 'Professor', respostas_incorretas: ['Chefe', 'Comandante', 'Diretor'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Em The Simpsons, a cidade onde vivem é:', resposta_correta: 'Springfield', respostas_incorretas: ['Shelbyville', 'Quahog', 'South Park'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Em Grey\'s Anatomy, a história se passa em um:', resposta_correta: 'Hospital', respostas_incorretas: ['Tribunal', 'Aeroporto', 'Restaurante'] },
  { categoria: 'Séries', dificuldade: 'medio', pontuacao: 20, pergunta: 'Em The Big Bang Theory, qual personagem é físico teórico?', resposta_correta: 'Sheldon Cooper', respostas_incorretas: ['Howard Wolowitz', 'Raj Koothrappali', 'Leonard Hofstadter'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o personagem principal da série Sherlock?', resposta_correta: 'Sherlock Holmes', respostas_incorretas: ['John Watson', 'Mycroft Holmes', 'Moriarty'] },
  { categoria: 'Séries', dificuldade: 'medio', pontuacao: 20, pergunta: 'A série Dark é de qual país?', resposta_correta: 'Alemanha', respostas_incorretas: ['Dinamarca', 'Suécia', 'Noruega'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Em Stranger Things, o mundo paralelo se chama:', resposta_correta: 'Mundo Invertido', respostas_incorretas: ['Outra Dimensão', 'Inferno', 'Upside Down City'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual série acompanha um grupo de cientistas e nerds?', resposta_correta: 'The Big Bang Theory', respostas_incorretas: ['Friends', 'How I Met Your Mother', 'The Office'] },
  { categoria: 'Séries', dificuldade: 'medio', pontuacao: 20, pergunta: 'Em La Casa de Papel, qual é o nome da narradora?', resposta_correta: 'Tóquio', respostas_incorretas: ['Nairóbi', 'Lisboa', 'Berlim'] },
  { categoria: 'Séries', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Em Friends, quem é a irmã gêmea de Phoebe?', resposta_correta: 'Ursula', respostas_incorretas: ['Emily', 'Rachel', 'Janice'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual série tem o personagem Michael Scott?', resposta_correta: 'The Office (US)', respostas_incorretas: ['Parks and Recreation', 'Brooklyn Nine-Nine', 'Community'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Em Breaking Bad, qual é o apelido de Walter White?', resposta_correta: 'Heisenberg', respostas_incorretas: ['Gus', 'Saul', 'Jesse'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual série se passa em um mundo pós-apocalíptico com zumbis?', resposta_correta: 'The Walking Dead', respostas_incorretas: ['Lost', 'Vikings', 'The 100'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual série tem o personagem Eleven?', resposta_correta: 'Stranger Things', respostas_incorretas: ['Dark', 'The 100', 'Riverdale'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual série é sobre um professor de química que vira criminoso?', resposta_correta: 'Breaking Bad', respostas_incorretas: ['Ozark', 'Narcos', 'The Wire'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Em The Simpsons, qual é o nome do pai da família?', resposta_correta: 'Homer Simpson', respostas_incorretas: ['Bart Simpson', 'Ned Flanders', 'Moe Szyslak'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Em Grey\'s Anatomy, qual é a profissão principal dos personagens?', resposta_correta: 'Médicos', respostas_incorretas: ['Policiais', 'Advogados', 'Jornalistas'] },
  { categoria: 'Séries', dificuldade: 'medio', pontuacao: 20, pergunta: 'Em Game of Thrones, o trono principal é feito de:', resposta_correta: 'Espadas', respostas_incorretas: ['Ouro', 'Pedras', 'Madeira'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual série tem um personagem chamado Sherlock Holmes?', resposta_correta: 'Sherlock', respostas_incorretas: ['House', 'Dexter', 'Suits'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual série acompanha um grupo de sobreviventes em uma ilha?', resposta_correta: 'Lost', respostas_incorretas: ['The 100', 'Vikings', 'Suits'] },
  { categoria: 'Séries', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual série tem o personagem Dexter Morgan?', resposta_correta: 'Dexter', respostas_incorretas: ['House', 'Sons of Anarchy', 'The Mentalist'] },

  // Perguntas adicionais de Séries - Difícil
  { categoria: 'Séries', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual ator interpretou Tyrion Lannister em Game of Thrones?', resposta_correta: 'Peter Dinklage', respostas_incorretas: ['Sean Bean', 'Kit Harington', 'Nikolaj Coster-Waldau'] },
  { categoria: 'Séries', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o nome verdadeiro de Heisenberg em Breaking Bad?', resposta_correta: 'Walter Hartwell White', respostas_incorretas: ['Walter Henry White', 'Walter Harold White', 'Walter Hamilton White'] },
  { categoria: 'Séries', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Em que ano estreou a primeira temporada de Friends?', resposta_correta: '1994', respostas_incorretas: ['1993', '1995', '1992'] },
  { categoria: 'Séries', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual série tem o personagem Don Draper?', resposta_correta: 'Mad Men', respostas_incorretas: ['Suits', 'The West Wing', 'House of Cards'] },
  { categoria: 'Séries', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o nome da empresa farmacêutica em Breaking Bad?', resposta_correta: 'Gray Matter', respostas_incorretas: ['Los Pollos Hermanos', 'Madrigal', 'Vamonos Pest'] },
  { categoria: 'Séries', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual ator interpretou Sherlock Holmes na série da BBC?', resposta_correta: 'Benedict Cumberbatch', respostas_incorretas: ['Martin Freeman', 'Robert Downey Jr.', 'Jonny Lee Miller'] },
  { categoria: 'Séries', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Em que cidade se passa a série The Wire?', resposta_correta: 'Baltimore', respostas_incorretas: ['Detroit', 'Chicago', 'Filadélfia'] },
  { categoria: 'Séries', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual série tem o personagem Rust Cohle?', resposta_correta: 'True Detective', respostas_incorretas: ['Fargo', 'Mindhunter', 'Hannibal'] },
  { categoria: 'Séries', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Quantas temporadas teve a série Lost?', resposta_correta: '6', respostas_incorretas: ['5', '7', '8'] },

  // Música (30)
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual instrumento tem teclas pretas e brancas?', resposta_correta: 'Piano', respostas_incorretas: ['Violão', 'Flauta', 'Bateria'] },
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual instrumento possui geralmente seis cordas?', resposta_correta: 'Violão', respostas_incorretas: ['Violino', 'Harpa', 'Flauta'] },
  { categoria: 'Música', dificuldade: 'medio', pontuacao: 20, pergunta: 'Quem compôs "Für Elise"?', resposta_correta: 'Beethoven', respostas_incorretas: ['Mozart', 'Bach', 'Chopin'] },
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quem cantou o álbum Thriller?', resposta_correta: 'Michael Jackson', respostas_incorretas: ['Prince', 'Elvis Presley', 'Madonna'] },
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual banda cantou "Hey Jude"?', resposta_correta: 'The Beatles', respostas_incorretas: ['The Rolling Stones', 'Queen', 'U2'] },
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual cantora lançou "Rolling in the Deep"?', resposta_correta: 'Adele', respostas_incorretas: ['Beyoncé', 'Rihanna', 'Taylor Swift'] },
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'O samba é um gênero musical originário de qual país?', resposta_correta: 'Brasil', respostas_incorretas: ['Cuba', 'México', 'Espanha'] },
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a nota musical após dó?', resposta_correta: 'Ré', respostas_incorretas: ['Mi', 'Fá', 'Si'] },
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é um instrumento de percussão?', resposta_correta: 'Bateria', respostas_incorretas: ['Violino', 'Clarinete', 'Harpa'] },
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quem é conhecido como o Rei do Pop?', resposta_correta: 'Michael Jackson', respostas_incorretas: ['Freddie Mercury', 'Elton John', 'Bruno Mars'] },
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quem é conhecida como a Rainha do Pop?', resposta_correta: 'Madonna', respostas_incorretas: ['Lady Gaga', 'Britney Spears', 'Adele'] },
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual país é considerado o berço do rock and roll?', resposta_correta: 'Estados Unidos', respostas_incorretas: ['Reino Unido', 'Canadá', 'Austrália'] },
  { categoria: 'Música', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é o instrumento usado para tocar música em um DJ set tradicional?', resposta_correta: 'Toca-discos', respostas_incorretas: ['Gaita', 'Sanfona', 'Piano'] },
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual instrumento é conhecido por seu som de sopro metálico?', resposta_correta: 'Trompete', respostas_incorretas: ['Violoncelo', 'Bateria', 'Guitarra'] },
  { categoria: 'Música', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é a clave mais usada para instrumentos melódicos?', resposta_correta: 'Clave de Sol', respostas_incorretas: ['Clave de Fá', 'Clave de Dó', 'Clave de Ré'] },
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual instrumento é típico do forró e da sanfona?', resposta_correta: 'Acordeão', respostas_incorretas: ['Violino', 'Guitarra', 'Flauta'] },
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual instrumento é tocado com baquetas?', resposta_correta: 'Bateria', respostas_incorretas: ['Violão', 'Flauta', 'Teclado'] },
  { categoria: 'Música', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual banda lançou o álbum The Dark Side of the Moon?', resposta_correta: 'Pink Floyd', respostas_incorretas: ['Nirvana', 'Metallica', 'AC/DC'] },
  { categoria: 'Música', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual cantor é conhecido como Rei do Baião?', resposta_correta: 'Luiz Gonzaga', respostas_incorretas: ['Dominguinhos', 'Gilberto Gil', 'Roberto Carlos'] },
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual instrumento é de sopro?', resposta_correta: 'Saxofone', respostas_incorretas: ['Violão', 'Piano', 'Bateria'] },
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual estilo musical é associado a DJs e batidas eletrônicas?', resposta_correta: 'Eletrônica', respostas_incorretas: ['Samba', 'Clássica', 'Folk'] },
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quem canta "Ai se eu te pego"?', resposta_correta: 'Michel Teló', respostas_incorretas: ['Gusttavo Lima', 'Luan Santana', 'Zezé Di Camargo'] },
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual cantora lançou "Bad Guy"?', resposta_correta: 'Billie Eilish', respostas_incorretas: ['Ariana Grande', 'Dua Lipa', 'Sia'] },
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual instrumento é típico de orquestras e tem quatro cordas?', resposta_correta: 'Violino', respostas_incorretas: ['Violão', 'Harpa', 'Pandeiro'] },
  { categoria: 'Música', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual gênero musical é conhecido por improvisos?', resposta_correta: 'Jazz', respostas_incorretas: ['Sertanejo', 'Pop', 'Forró'] },
  { categoria: 'Música', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual instrumento tem 88 teclas?', resposta_correta: 'Piano', respostas_incorretas: ['Órgão', 'Teclado', 'Acordeão'] },
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual estilo musical é típico do Nordeste do Brasil?', resposta_correta: 'Forró', respostas_incorretas: ['Sertanejo', 'MPB', 'Samba'] },
  { categoria: 'Música', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual instrumento é usado em músicas de carnaval com som agudo?', resposta_correta: 'Tamborim', respostas_incorretas: ['Surdo', 'Pandeiro', 'Timbau'] },
  { categoria: 'Música', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual cantora brasileira ficou famosa com "Malandragem"?', resposta_correta: 'Cássia Eller', respostas_incorretas: ['Rita Lee', 'Elis Regina', 'Gal Costa'] },
  { categoria: 'Música', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual cantor é conhecido como Rei da Jovem Guarda?', resposta_correta: 'Roberto Carlos', respostas_incorretas: ['Erasmo Carlos', 'Tim Maia', 'Caetano Veloso'] },

  // Perguntas adicionais de Música - Difícil
  { categoria: 'Música', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual compositor escreveu "A Nona Sinfonia"?', resposta_correta: 'Beethoven', respostas_incorretas: ['Mozart', 'Bach', 'Brahms'] },
  { categoria: 'Música', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual banda lançou o álbum "OK Computer"?', resposta_correta: 'Radiohead', respostas_incorretas: ['Coldplay', 'Muse', 'Oasis'] },
  { categoria: 'Música', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o nome verdadeiro de Freddie Mercury?', resposta_correta: 'Farrokh Bulsara', respostas_incorretas: ['Frederick Mercury', 'Freddie Bulsara', 'Farrokh Mercury'] },
  { categoria: 'Música', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual instrumento Miles Davis tocava?', resposta_correta: 'Trompete', respostas_incorretas: ['Saxofone', 'Piano', 'Contrabaixo'] },
  { categoria: 'Música', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é a tonalidade de "Imagine" do John Lennon?', resposta_correta: 'Dó maior', respostas_incorretas: ['Sol maior', 'Fá maior', 'Lá maior'] },
  { categoria: 'Música', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual banda criou o álbum "The Wall"?', resposta_correta: 'Pink Floyd', respostas_incorretas: ['Led Zeppelin', 'The Who', 'Deep Purple'] },
  { categoria: 'Música', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual compositor brasileiro escreveu "Aquarela do Brasil"?', resposta_correta: 'Ary Barroso', respostas_incorretas: ['Tom Jobim', 'Dorival Caymmi', 'Pixinguinha'] },
  { categoria: 'Música', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o nome do primeiro álbum dos Beatles?', resposta_correta: 'Please Please Me', respostas_incorretas: ['Love Me Do', 'Help!', 'A Hard Day\'s Night'] },
  { categoria: 'Música', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual cantora é conhecida como "A Voz"?', resposta_correta: 'Whitney Houston', respostas_incorretas: ['Mariah Carey', 'Celine Dion', 'Aretha Franklin'] },

  // História (30)
  { categoria: 'História', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quem chegou ao Brasil em 1500?', resposta_correta: 'Pedro Álvares Cabral', respostas_incorretas: ['Cristóvão Colombo', 'Vasco da Gama', 'Dom Pedro I'] },
  { categoria: 'História', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quem proclamou a Independência do Brasil?', resposta_correta: 'Dom Pedro I', respostas_incorretas: ['Dom Pedro II', 'Tiradentes', 'Getúlio Vargas'] },
  { categoria: 'História', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quem assinou a Lei Áurea?', resposta_correta: 'Princesa Isabel', respostas_incorretas: ['Dom Pedro I', 'Getúlio Vargas', 'Rui Barbosa'] },
  { categoria: 'História', dificuldade: 'facil', pontuacao: 10, pergunta: 'Em que país começou a Revolução Francesa?', resposta_correta: 'França', respostas_incorretas: ['Inglaterra', 'Espanha', 'Itália'] },
  { categoria: 'História', dificuldade: 'facil', pontuacao: 10, pergunta: 'Em que período ocorreu a Primeira Guerra Mundial?', resposta_correta: '1914-1918', respostas_incorretas: ['1939-1945', '1900-1905', '1929-1933'] },
  { categoria: 'História', dificuldade: 'facil', pontuacao: 10, pergunta: 'Em que período ocorreu a Segunda Guerra Mundial?', resposta_correta: '1939-1945', respostas_incorretas: ['1914-1918', '1950-1953', '1964-1969'] },
  { categoria: 'História', dificuldade: 'medio', pontuacao: 20, pergunta: 'Em que ano caiu o Muro de Berlim?', resposta_correta: '1989', respostas_incorretas: ['1979', '1999', '1969'] },
  { categoria: 'História', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quem descobriu a América em 1492?', resposta_correta: 'Cristóvão Colombo', respostas_incorretas: ['Pedro Álvares Cabral', 'Américo Vespúcio', 'Vasco da Gama'] },
  { categoria: 'História', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quem era o líder da Inconfidência Mineira?', resposta_correta: 'Tiradentes', respostas_incorretas: ['Dom Pedro I', 'Zumbi dos Palmares', 'Duque de Caxias'] },
  { categoria: 'História', dificuldade: 'facil', pontuacao: 10, pergunta: 'Em que país começou a Revolução Industrial?', resposta_correta: 'Inglaterra', respostas_incorretas: ['França', 'Alemanha', 'Itália'] },
  { categoria: 'História', dificuldade: 'medio', pontuacao: 20, pergunta: 'Quem foi o primeiro presidente do Brasil?', resposta_correta: 'Deodoro da Fonseca', respostas_incorretas: ['Floriano Peixoto', 'Getúlio Vargas', 'Dom Pedro II'] },
  { categoria: 'História', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual era a língua oficial do Império Romano?', resposta_correta: 'Latim', respostas_incorretas: ['Grego', 'Francês', 'Alemão'] },
  { categoria: 'História', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Como se chamava a escrita da Mesopotâmia?', resposta_correta: 'Cuneiforme', respostas_incorretas: ['Hieróglifos', 'Alfabeto latino', 'Runas'] },
  { categoria: 'História', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quem era o governante máximo do Egito Antigo?', resposta_correta: 'Faraó', respostas_incorretas: ['Cônsul', 'Imperador', 'Rei Arthur'] },
  { categoria: 'História', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual era a principal civilização da Grécia Antiga famosa por sua democracia?', resposta_correta: 'Atenas', respostas_incorretas: ['Esparta', 'Roma', 'Cartago'] },
  { categoria: 'História', dificuldade: 'facil', pontuacao: 10, pergunta: 'Em que ano o Brasil se tornou República?', resposta_correta: '1889', respostas_incorretas: ['1822', '1930', '1964'] },
  { categoria: 'História', dificuldade: 'medio', pontuacao: 20, pergunta: 'Quem foi o líder da Revolução Cubana?', resposta_correta: 'Fidel Castro', respostas_incorretas: ['Che Guevara', 'Simón Bolívar', 'Allende'] },
  { categoria: 'História', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual foi o período da Ditadura Militar no Brasil?', resposta_correta: '1964-1985', respostas_incorretas: ['1930-1945', '1950-1960', '1985-1990'] },
  { categoria: 'História', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quem foi o líder da Alemanha na Segunda Guerra Mundial?', resposta_correta: 'Adolf Hitler', respostas_incorretas: ['Stalin', 'Mussolini', 'Churchill'] },
  { categoria: 'História', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual civilização construiu as pirâmides de Gizé?', resposta_correta: 'Egípcios', respostas_incorretas: ['Maias', 'Romanos', 'Gregos'] },
  { categoria: 'História', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quem foi o primeiro imperador do Brasil?', resposta_correta: 'Dom Pedro I', respostas_incorretas: ['Dom Pedro II', 'Getúlio Vargas', 'Deodoro'] },
  { categoria: 'História', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual país foi o berço da democracia moderna?', resposta_correta: 'Grécia', respostas_incorretas: ['Roma', 'Egito', 'China'] },
  { categoria: 'História', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual era o nome da capital do Império Bizantino?', resposta_correta: 'Constantinopla', respostas_incorretas: ['Roma', 'Atenas', 'Alexandria'] },
  { categoria: 'História', dificuldade: 'medio', pontuacao: 20, pergunta: 'Quem liderou a marcha pela independência da Índia?', resposta_correta: 'Mahatma Gandhi', respostas_incorretas: ['Jawaharlal Nehru', 'Dalai Lama', 'Indira Gandhi'] },
  { categoria: 'História', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual civilização antiga era conhecida por suas pirâmides na América?', resposta_correta: 'Maias', respostas_incorretas: ['Vikings', 'Persas', 'Fenícios'] },
  { categoria: 'História', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quem foi o presidente do Brasil durante a Era Vargas?', resposta_correta: 'Getúlio Vargas', respostas_incorretas: ['Juscelino Kubitschek', 'João Goulart', 'Deodoro'] },
  { categoria: 'História', dificuldade: 'medio', pontuacao: 20, pergunta: 'O que foi a Guerra Fria?', resposta_correta: 'Disputa EUA x URSS', respostas_incorretas: ['Guerra na Europa', 'Guerra civil no Brasil', 'Conflito colonial'] },
  { categoria: 'História', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual país era liderado por Napoleão Bonaparte?', resposta_correta: 'França', respostas_incorretas: ['Inglaterra', 'Espanha', 'Portugal'] },
  { categoria: 'História', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual foi o estopim da Primeira Guerra Mundial?', resposta_correta: 'Assassinato do arquiduque Franz Ferdinand', respostas_incorretas: ['Invasão da Polônia', 'Queda do Muro de Berlim', 'Revolução Russa'] },
  { categoria: 'História', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quem foi o líder da União Soviética na Segunda Guerra?', resposta_correta: 'Stalin', respostas_incorretas: ['Lenin', 'Gorbachev', 'Trotsky'] },

  // Geografia (30)
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a capital da Argentina?', resposta_correta: 'Buenos Aires', respostas_incorretas: ['Santiago', 'Montevidéu', 'Lima'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o maior país do mundo em área?', resposta_correta: 'Rússia', respostas_incorretas: ['Canadá', 'China', 'Estados Unidos'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Em que continente fica o Deserto do Saara?', resposta_correta: 'África', respostas_incorretas: ['Ásia', 'Europa', 'América'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual rio corta o Egito?', resposta_correta: 'Nilo', respostas_incorretas: ['Amazonas', 'Danúbio', 'Ganges'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a capital da França?', resposta_correta: 'Paris', respostas_incorretas: ['Londres', 'Roma', 'Berlim'] },
  { categoria: 'Geografia', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual país NÃO faz fronteira com o Brasil?', resposta_correta: 'Chile', respostas_incorretas: ['Argentina', 'Peru', 'Colômbia'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Em qual continente está o Japão?', resposta_correta: 'Ásia', respostas_incorretas: ['Europa', 'América', 'Oceania'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o maior estado do Brasil em área?', resposta_correta: 'Amazonas', respostas_incorretas: ['Pará', 'Mato Grosso', 'Bahia'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual oceano banha a maior parte do litoral brasileiro?', resposta_correta: 'Atlântico', respostas_incorretas: ['Pacífico', 'Índico', 'Ártico'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual linha imaginária divide a Terra em hemisfério norte e sul?', resposta_correta: 'Linha do Equador', respostas_incorretas: ['Trópico de Câncer', 'Meridiano de Greenwich', 'Linha Internacional de Data'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o maior continente do mundo?', resposta_correta: 'Ásia', respostas_incorretas: ['África', 'Europa', 'América'] },
  { categoria: 'Geografia', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual país tem a maior população do mundo?', resposta_correta: 'Índia', respostas_incorretas: ['China', 'Estados Unidos', 'Indonésia'] },
  { categoria: 'Geografia', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é a capital do Canadá?', resposta_correta: 'Ottawa', respostas_incorretas: ['Toronto', 'Vancouver', 'Montreal'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o maior rio do mundo em extensão?', resposta_correta: 'Amazonas', respostas_incorretas: ['Nilo', 'Yangtzé', 'Mississippi'] },
  { categoria: 'Geografia', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual cadeia montanhosa separa a Europa da Ásia?', resposta_correta: 'Montes Urais', respostas_incorretas: ['Alpes', 'Himalaias', 'Andes'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a capital do Chile?', resposta_correta: 'Santiago', respostas_incorretas: ['Buenos Aires', 'La Paz', 'Quito'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual país tem a maior extensão territorial da América do Sul depois do Brasil?', resposta_correta: 'Argentina', respostas_incorretas: ['Peru', 'Colômbia', 'Chile'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a capital da Itália?', resposta_correta: 'Roma', respostas_incorretas: ['Milão', 'Veneza', 'Nápoles'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual país é conhecido como Terra do Sol Nascente?', resposta_correta: 'Japão', respostas_incorretas: ['China', 'Coreia do Sul', 'Tailândia'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a capital da Alemanha?', resposta_correta: 'Berlim', respostas_incorretas: ['Munique', 'Hamburgo', 'Frankfurt'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual país europeu tem Lisboa como capital?', resposta_correta: 'Portugal', respostas_incorretas: ['Espanha', 'Itália', 'França'] },
  { categoria: 'Geografia', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é o maior lago do mundo?', resposta_correta: 'Mar Cáspio', respostas_incorretas: ['Lago Superior', 'Lago Vitória', 'Lago Baikal'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Em qual continente fica o Brasil?', resposta_correta: 'América do Sul', respostas_incorretas: ['América do Norte', 'Europa', 'África'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o país mais populoso da América do Sul?', resposta_correta: 'Brasil', respostas_incorretas: ['Argentina', 'Colômbia', 'Peru'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual oceano fica entre África e Austrália?', resposta_correta: 'Índico', respostas_incorretas: ['Atlântico', 'Pacífico', 'Ártico'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a capital da Espanha?', resposta_correta: 'Madri', respostas_incorretas: ['Barcelona', 'Sevilha', 'Valência'] },
  { categoria: 'Geografia', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o país com mais ilhas no mundo?', resposta_correta: 'Suécia', respostas_incorretas: ['Indonésia', 'Filipinas', 'Noruega'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o menor país do mundo?', resposta_correta: 'Vaticano', respostas_incorretas: ['Mônaco', 'Malta', 'Andorra'] },
  { categoria: 'Geografia', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual país tem o maior número de fusos horários?', resposta_correta: 'França', respostas_incorretas: ['Rússia', 'Estados Unidos', 'China'] },
  { categoria: 'Geografia', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a capital do México?', resposta_correta: 'Cidade do México', respostas_incorretas: ['Guadalajara', 'Monterrey', 'Puebla'] },

  // Perguntas adicionais de Geografia - Médio
  { categoria: 'Geografia', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é a capital da Austrália?', resposta_correta: 'Canberra', respostas_incorretas: ['Sydney', 'Melbourne', 'Brisbane'] },
  { categoria: 'Geografia', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual país tem três capitais oficiais?', resposta_correta: 'África do Sul', respostas_incorretas: ['Bolívia', 'Holanda', 'Suíça'] },
  { categoria: 'Geografia', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é o estreito que separa a Europa da África?', resposta_correta: 'Estreito de Gibraltar', respostas_incorretas: ['Estreito de Bering', 'Canal da Mancha', 'Estreito de Ormuz'] },
  { categoria: 'Geografia', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é a capital da Nova Zelândia?', resposta_correta: 'Wellington', respostas_incorretas: ['Auckland', 'Christchurch', 'Hamilton'] },
  { categoria: 'Geografia', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual rio passa por Paris?', resposta_correta: 'Sena', respostas_incorretas: ['Tâmisa', 'Reno', 'Danúbio'] },
  { categoria: 'Geografia', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é a capital da Coréia do Sul?', resposta_correta: 'Seul', respostas_incorretas: ['Busan', 'Incheon', 'Daegu'] },

  // Perguntas adicionais de Geografia - Difícil
  { categoria: 'Geografia', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o ponto mais alto da América do Sul?', resposta_correta: 'Aconcagua', respostas_incorretas: ['Huascarán', 'Chimborazo', 'Cotopaxi'] },
  { categoria: 'Geografia', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual país é completamente cercado pela África do Sul?', resposta_correta: 'Lesoto', respostas_incorretas: ['Suazilândia', 'Botsuana', 'Maláui'] },
  { categoria: 'Geografia', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é a capital do Cazaquistão?', resposta_correta: 'Nur-Sultan', respostas_incorretas: ['Almaty', 'Shymkent', 'Aktobe'] },
  { categoria: 'Geografia', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o menor país da África?', resposta_correta: 'Seicheles', respostas_incorretas: ['Gamábia', 'Djibuti', 'Cabo Verde'] },
  { categoria: 'Geografia', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual mar fica entre a Grécia e a Turquia?', resposta_correta: 'Mar Egeu', respostas_incorretas: ['Mar Jônico', 'Mar Negro', 'Mar de Mármara'] },
  { categoria: 'Geografia', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é a capital de Mianmar?', resposta_correta: 'Naypyidaw', respostas_incorretas: ['Yangon', 'Mandalay', 'Bagan'] },
  { categoria: 'Geografia', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual arquipélago pertence ao Equador?', resposta_correta: 'Galápagos', respostas_incorretas: ['Malvinas', 'Açores', 'Canárias'] },

  // Matemática (30)
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quanto é 5 + 7?', resposta_correta: '12', respostas_incorretas: ['10', '11', '13'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quanto é 9 x 6?', resposta_correta: '54', respostas_incorretas: ['45', '56', '60'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quanto é 100 - 37?', resposta_correta: '63', respostas_incorretas: ['67', '73', '57'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o resultado de 12 ÷ 3?', resposta_correta: '4', respostas_incorretas: ['3', '6', '5'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o próximo número par após 20?', resposta_correta: '22', respostas_incorretas: ['21', '24', '23'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quanto é 8 x 8?', resposta_correta: '64', respostas_incorretas: ['56', '72', '62'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quanto é 49 ÷ 7?', resposta_correta: '7', respostas_incorretas: ['6', '8', '9'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o quadrado de 5?', resposta_correta: '25', respostas_incorretas: ['20', '15', '30'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quanto é 25 + 25?', resposta_correta: '50', respostas_incorretas: ['45', '55', '60'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quanto é 10% de 200?', resposta_correta: '20', respostas_incorretas: ['10', '30', '25'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quanto é 7 x 9?', resposta_correta: '63', respostas_incorretas: ['56', '72', '69'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o resultado de 81 ÷ 9?', resposta_correta: '9', respostas_incorretas: ['8', '7', '6'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a metade de 100?', resposta_correta: '50', respostas_incorretas: ['25', '40', '60'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quanto é 3²?', resposta_correta: '9', respostas_incorretas: ['6', '12', '8'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quanto é 15 - 4?', resposta_correta: '11', respostas_incorretas: ['9', '10', '12'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quanto é 15 + 27?', resposta_correta: '42', respostas_incorretas: ['40', '45', '47'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quanto é 8 x 7?', resposta_correta: '56', respostas_incorretas: ['49', '63', '54'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o resultado de 2³?', resposta_correta: '8', respostas_incorretas: ['6', '9', '12'] },
  { categoria: 'Matemática', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é o próximo número primo após 17?', resposta_correta: '19', respostas_incorretas: ['21', '23', '18'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quanto é 14% de 100?', resposta_correta: '14', respostas_incorretas: ['10', '12', '16'] },
  { categoria: 'Matemática', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é o valor de 5³?', resposta_correta: '125', respostas_incorretas: ['25', '75', '100'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quanto é 6 x 6?', resposta_correta: '36', respostas_incorretas: ['30', '32', '42'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quanto é 100 ÷ 5?', resposta_correta: '20', respostas_incorretas: ['10', '15', '25'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quanto é 3,5 + 2,5?', resposta_correta: '6', respostas_incorretas: ['5', '7', '4'] },
  { categoria: 'Matemática', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é a fração equivalente a 1/2?', resposta_correta: '2/4', respostas_incorretas: ['3/5', '1/3', '4/5'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o ângulo reto?', resposta_correta: '90°', respostas_incorretas: ['45°', '180°', '60°'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quanto é 0,2 em porcentagem?', resposta_correta: '20%', respostas_incorretas: ['2%', '10%', '200%'] },
  { categoria: 'Matemática', dificuldade: 'medio', pontuacao: 20, pergunta: 'Quanto é 11 x 11?', resposta_correta: '121', respostas_incorretas: ['111', '110', '112'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a raiz quadrada de 64?', resposta_correta: '8', respostas_incorretas: ['6', '7', '9'] },
  { categoria: 'Matemática', dificuldade: 'facil', pontuacao: 10, pergunta: 'Quanto é 12 + 8?', resposta_correta: '20', respostas_incorretas: ['18', '22', '21'] },

  // Perguntas adicionais de Matemática - Médio
  { categoria: 'Matemática', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é o resultado de 15% de 80?', resposta_correta: '12', respostas_incorretas: ['10', '15', '8'] },
  { categoria: 'Matemática', dificuldade: 'medio', pontuacao: 20, pergunta: 'Quanto é a raiz quadrada de 144?', resposta_correta: '12', respostas_incorretas: ['10', '14', '16'] },
  { categoria: 'Matemática', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é o perímetro de um retângulo de 5cm x 3cm?', resposta_correta: '16cm', respostas_incorretas: ['15cm', '18cm', '12cm'] },
  { categoria: 'Matemática', dificuldade: 'medio', pontuacao: 20, pergunta: 'Quanto é 7² - 3²?', resposta_correta: '40', respostas_incorretas: ['42', '38', '36'] },
  { categoria: 'Matemática', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é a área de um círculo com raio 3?', resposta_correta: '9π', respostas_incorretas: ['6π', '12π', '3π'] },
  { categoria: 'Matemática', dificuldade: 'medio', pontuacao: 20, pergunta: 'Quanto é 25% de 120?', resposta_correta: '30', respostas_incorretas: ['25', '35', '20'] },

  // Perguntas adicionais de Matemática - Difícil
  { categoria: 'Matemática', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é a derivada de x³?', resposta_correta: '3x²', respostas_incorretas: ['x²', '3x', 'x³/3'] },
  { categoria: 'Matemática', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Quanto é log₁₀(1000)?', resposta_correta: '3', respostas_incorretas: ['10', '100', '30'] },
  { categoria: 'Matemática', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o valor de sen(90°)?', resposta_correta: '1', respostas_incorretas: ['0', '0,5', '√2/2'] },
  { categoria: 'Matemática', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é a fórmula da área do triângulo?', resposta_correta: 'base x altura / 2', respostas_incorretas: ['base x altura', 'base + altura / 2', 'base x altura x 2'] },
  { categoria: 'Matemática', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Quanto é a integral de 2x?', resposta_correta: 'x² + C', respostas_incorretas: ['2x² + C', 'x + C', '2 + C'] },
  { categoria: 'Matemática', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o valor de cos(60°)?', resposta_correta: '0,5', respostas_incorretas: ['1', '√3/2', '√2/2'] },
  { categoria: 'Matemática', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é a fórmula de Bháskara?', resposta_correta: 'x = (-b ± √Δ) / 2a', respostas_incorretas: ['x = -b / 2a', 'x = b² - 4ac', 'x = a + b + c'] },
  { categoria: 'Matemática', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Quanto é 4! (4 fatorial)?', resposta_correta: '24', respostas_incorretas: ['16', '12', '8'] },
  { categoria: 'Matemática', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o valor de π (pi) aproximadamente?', resposta_correta: '3,14159', respostas_incorretas: ['3,14', '3,1416', '3,15'] },
  { categoria: 'Matemática', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é a soma dos ângulos internos de um triângulo?', resposta_correta: '180°', respostas_incorretas: ['360°', '90°', '270°'] },

  // Ciência (30)
  { categoria: 'Ciência', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o planeta conhecido como planeta azul?', resposta_correta: 'Terra', respostas_incorretas: ['Netuno', 'Urano', 'Vênus'] },
  { categoria: 'Ciência', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual órgão é responsável pela visão?', resposta_correta: 'Olhos', respostas_incorretas: ['Ouvidos', 'Pulmões', 'Coração'] },
  { categoria: 'Ciência', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual cientista propôs a teoria da relatividade?', resposta_correta: 'Albert Einstein', respostas_incorretas: ['Newton', 'Galileu', 'Darwin'] },
  { categoria: 'Ciência', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a fonte principal de energia da Terra?', resposta_correta: 'Sol', respostas_incorretas: ['Lua', 'Vento', 'Mar'] },
  { categoria: 'Ciência', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o estado físico do vapor de água?', resposta_correta: 'Gasoso', respostas_incorretas: ['Líquido', 'Sólido', 'Plasma'] },
  { categoria: 'Ciência', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual mineral é essencial para ossos fortes?', resposta_correta: 'Cálcio', respostas_incorretas: ['Sódio', 'Potássio', 'Ferro'] },
  { categoria: 'Ciência', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o maior planeta do Sistema Solar?', resposta_correta: 'Júpiter', respostas_incorretas: ['Saturno', 'Terra', 'Marte'] },
  { categoria: 'Ciência', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o processo de passagem do sólido para o gasoso?', resposta_correta: 'Sublimação', respostas_incorretas: ['Fusão', 'Evaporação', 'Condensação'] },
  { categoria: 'Ciência', dificuldade: 'medio', pontuacao: 20, pergunta: 'O que mede um barômetro?', resposta_correta: 'Pressão atmosférica', respostas_incorretas: ['Temperatura', 'Umidade', 'Vento'] },
  { categoria: 'Ciência', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o maior planeta rochoso?', resposta_correta: 'Terra', respostas_incorretas: ['Marte', 'Mercúrio', 'Vênus'] },
  { categoria: 'Ciência', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o nome da nossa galáxia?', resposta_correta: 'Via Láctea', respostas_incorretas: ['Andrômeda', 'Sombrero', 'Triângulo'] },
  { categoria: 'Ciência', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual órgão filtra o sangue?', resposta_correta: 'Rins', respostas_incorretas: ['Pulmões', 'Fígado', 'Coração'] },
  { categoria: 'Ciência', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual gás é usado em balões para fazê-los flutuar?', resposta_correta: 'Hélio', respostas_incorretas: ['Oxigênio', 'Nitrogênio', 'Gás carbônico'] },
  { categoria: 'Ciência', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a principal função do pulmão?', resposta_correta: 'Troca de gases', respostas_incorretas: ['Digestão', 'Circulação', 'Filtração'] },
  { categoria: 'Ciência', dificuldade: 'medio', pontuacao: 20, pergunta: 'O DNA está localizado em qual parte da célula?', resposta_correta: 'Núcleo', respostas_incorretas: ['Citoplasma', 'Membrana', 'Mitocôndria'] },
  { categoria: 'Ciência', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o maior órgão do corpo humano?', resposta_correta: 'Pele', respostas_incorretas: ['Fígado', 'Coração', 'Pulmão'] },
  { categoria: 'Ciência', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual planeta é conhecido como planeta vermelho?', resposta_correta: 'Marte', respostas_incorretas: ['Júpiter', 'Vênus', 'Saturno'] },
  { categoria: 'Ciência', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é o processo de transformação de líquido em gasoso?', resposta_correta: 'Evaporação', respostas_incorretas: ['Fusão', 'Condensação', 'Sublimação'] },
  { categoria: 'Ciência', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é o metal líquido à temperatura ambiente?', resposta_correta: 'Mercúrio', respostas_incorretas: ['Ferro', 'Alumínio', 'Cobre'] },
  { categoria: 'Ciência', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual é a camada mais externa da Terra?', resposta_correta: 'Crosta', respostas_incorretas: ['Manto', 'Núcleo', 'Litosfera'] },
  { categoria: 'Ciência', dificuldade: 'facil', pontuacao: 10, pergunta: 'O que é fotossíntese?', resposta_correta: 'Processo de produção de alimento pelas plantas', respostas_incorretas: ['Respiração celular', 'Digestão', 'Fermentação'] },
  { categoria: 'Ciência', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é a unidade de medida da força?', resposta_correta: 'Newton', respostas_incorretas: ['Joule', 'Watt', 'Pascal'] },
  { categoria: 'Ciência', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual gás é essencial para a respiração humana?', resposta_correta: 'Oxigênio', respostas_incorretas: ['Nitrogênio', 'Hélio', 'Hidrogênio'] },
  { categoria: 'Ciência', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é a velocidade aproximada da luz no vácuo?', resposta_correta: '300 mil km/s', respostas_incorretas: ['150 mil km/s', '450 mil km/s', '30 mil km/s'] },
  { categoria: 'Ciência', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual órgão é responsável por bombear o sangue?', resposta_correta: 'Coração', respostas_incorretas: ['Pulmões', 'Rins', 'Fígado'] },
  { categoria: 'Ciência', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual sistema do corpo controla hormônios?', resposta_correta: 'Endócrino', respostas_incorretas: ['Nervoso', 'Digestivo', 'Respiratório'] },
  { categoria: 'Ciência', dificuldade: 'facil', pontuacao: 10, pergunta: 'O que mede um termômetro?', resposta_correta: 'Temperatura', respostas_incorretas: ['Pressão', 'Umidade', 'Altura'] },
  { categoria: 'Ciência', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o menor osso do corpo humano?', resposta_correta: 'Estribo', respostas_incorretas: ['Fêmur', 'Rádio', 'Úmero'] },
  { categoria: 'Ciência', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual é a unidade básica da matéria?', resposta_correta: 'Átomo', respostas_incorretas: ['Célula', 'Molécula', 'Partícula'] },
  { categoria: 'Ciência', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual planeta é famoso por seus anéis?', resposta_correta: 'Saturno', respostas_incorretas: ['Júpiter', 'Urano', 'Netuno'] },

  // Jogos (30)
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo tem o personagem Link?', resposta_correta: 'The Legend of Zelda', respostas_incorretas: ['Metroid', 'Mario', 'Kirby'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo é conhecido por construir cidades e simulação de vida?', resposta_correta: 'The Sims', respostas_incorretas: ['Minecraft', 'Stardew Valley', 'Terraria'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo se passa no universo Pokémon e é de RPG?', resposta_correta: 'Pokémon', respostas_incorretas: ['Digimon', 'Temtem', 'Yo-kai Watch'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo tem o personagem Sonic?', resposta_correta: 'Sonic the Hedgehog', respostas_incorretas: ['Mario', 'Crash Bandicoot', 'Spyro'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo tem o personagem Kratos em mitologia nórdica?', resposta_correta: 'God of War', respostas_incorretas: ['Skyrim', 'Assassin\'s Creed', 'The Witcher'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo de tiro tático é da Valve?', resposta_correta: 'Counter-Strike', respostas_incorretas: ['Valorant', 'Overwatch', 'Fortnite'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo tem o modo creative e survival?', resposta_correta: 'Minecraft', respostas_incorretas: ['Roblox', 'Terraria', 'ARK'] },
  { categoria: 'Jogos', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual jogo é famoso pelo mapa Summoner\'s Rift?', resposta_correta: 'League of Legends', respostas_incorretas: ['Dota 2', 'Smite', 'Heroes of the Storm'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo de corrida é conhecido por carros realistas e pistas reais?', resposta_correta: 'Gran Turismo', respostas_incorretas: ['Mario Kart', 'Need for Speed', 'Forza Horizon'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo tem o personagem Pikachu?', resposta_correta: 'Pokémon', respostas_incorretas: ['Digimon', 'Zelda', 'Sonic'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo é um battle royale da Activision?', resposta_correta: 'Warzone', respostas_incorretas: ['Fortnite', 'PUBG', 'Apex Legends'] },
  { categoria: 'Jogos', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual jogo tem o personagem Arthur Morgan?', resposta_correta: 'Red Dead Redemption 2', respostas_incorretas: ['GTA V', 'Max Payne', 'Bully'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo de luta tem personagens como Ryu e Ken?', resposta_correta: 'Street Fighter', respostas_incorretas: ['Mortal Kombat', 'Tekken', 'Smash Bros'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo tem o personagem Steve?', resposta_correta: 'Minecraft', respostas_incorretas: ['Terraria', 'Roblox', 'Among Us'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo é focado em construção de fazenda?', resposta_correta: 'Stardew Valley', respostas_incorretas: ['The Sims', 'Minecraft', 'Animal Crossing'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo tem um encanador chamado Mario?', resposta_correta: 'Super Mario Bros', respostas_incorretas: ['Sonic', 'Kirby', 'Megaman'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo é de blocos e construção livre?', resposta_correta: 'Minecraft', respostas_incorretas: ['Terraria', 'Roblox', 'No Man\'s Sky'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo se passa em Los Santos?', resposta_correta: 'GTA V', respostas_incorretas: ['Mafia', 'Watch Dogs', 'Saints Row'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo tem o personagem Master Chief?', resposta_correta: 'Halo', respostas_incorretas: ['Destiny', 'Doom', 'Call of Duty'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo é conhecido por capturar monstros em esferas?', resposta_correta: 'Pokémon', respostas_incorretas: ['Digimon', 'Temtem', 'Monster Hunter'] },
  { categoria: 'Jogos', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual jogo é da franquia de futebol da EA?', resposta_correta: 'EA Sports FC', respostas_incorretas: ['eFootball', 'PES', 'Rocket League'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo tem o personagem Lara Croft?', resposta_correta: 'Tomb Raider', respostas_incorretas: ['Uncharted', 'Resident Evil', 'Silent Hill'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo é conhecido por batalhas em arena com heróis?', resposta_correta: 'Overwatch', respostas_incorretas: ['Valorant', 'CS:GO', 'PUBG'] },
  { categoria: 'Jogos', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual jogo tem o modo battle royale chamado Verdansk?', resposta_correta: 'Warzone', respostas_incorretas: ['Fortnite', 'PUBG', 'Apex Legends'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo tem corridas em karts com itens?', resposta_correta: 'Mario Kart', respostas_incorretas: ['Gran Turismo', 'Forza', 'Need for Speed'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo se passa em Hyrule?', resposta_correta: 'The Legend of Zelda', respostas_incorretas: ['Fire Emblem', 'Metroid', 'Kirby'] },
  { categoria: 'Jogos', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual jogo tem um caçador de monstros chamado Geralt?', resposta_correta: 'The Witcher 3', respostas_incorretas: ['Skyrim', 'Dragon Age', 'Elden Ring'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo é sobre batalhas entre times em uma arena?', resposta_correta: 'League of Legends', respostas_incorretas: ['Fortnite', 'Minecraft', 'FIFA'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo é sobre sobrevivência em um mundo de zumbis?', resposta_correta: 'The Last of Us', respostas_incorretas: ['God of War', 'Horizon', 'FIFA'] },
  { categoria: 'Jogos', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual jogo tem a personagem Samus Aran?', resposta_correta: 'Metroid', respostas_incorretas: ['Zelda', 'Halo', 'Doom'] },

  // Perguntas adicionais de Jogos - Difícil
  { categoria: 'Jogos', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual empresa criou o jogo Half-Life?', resposta_correta: 'Valve', respostas_incorretas: ['Blizzard', 'id Software', 'Epic Games'] },
  { categoria: 'Jogos', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Em que ano foi lançado o primeiro Super Mario Bros?', resposta_correta: '1985', respostas_incorretas: ['1983', '1987', '1984'] },
  { categoria: 'Jogos', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o nome do protagonista de Metal Gear Solid?', resposta_correta: 'Solid Snake', respostas_incorretas: ['Big Boss', 'Raiden', 'Gray Fox'] },
  { categoria: 'Jogos', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual jogo popularizou o gênero battle royale?', resposta_correta: 'PlayerUnknown\'s Battlegrounds', respostas_incorretas: ['Fortnite', 'Apex Legends', 'H1Z1'] },
  { categoria: 'Jogos', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o nome do criador de Minecraft?', resposta_correta: 'Markus Persson (Notch)', respostas_incorretas: ['Jens Bergensten', 'Carl Manneh', 'Jakob Porser'] },
  { categoria: 'Jogos', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual jogo tem o personagem Kratos antes da mitologia nórdica?', resposta_correta: 'God of War (mitologia grega)', respostas_incorretas: ['Dante\'s Inferno', 'Bayonetta', 'Devil May Cry'] },
  { categoria: 'Jogos', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o nome da empresa que criou World of Warcraft?', resposta_correta: 'Blizzard Entertainment', respostas_incorretas: ['Activision', 'Electronic Arts', 'Ubisoft'] },
  { categoria: 'Jogos', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual jogo tem o personagem Gordon Freeman?', resposta_correta: 'Half-Life', respostas_incorretas: ['Portal', 'Left 4 Dead', 'Team Fortress'] },
  { categoria: 'Jogos', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Em que ano foi lançado o primeiro The Legend of Zelda?', resposta_correta: '1986', respostas_incorretas: ['1985', '1987', '1988'] },
  { categoria: 'Jogos', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o nome do antagonista principal em Final Fantasy VII?', resposta_correta: 'Sephiroth', respostas_incorretas: ['Kefka', 'Ultimecia', 'Kuja'] },

  // Esportes (30)
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte usa bola oval?', resposta_correta: 'Rugby', respostas_incorretas: ['Futebol', 'Basquete', 'Vôlei'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte tem cestas e tabelas?', resposta_correta: 'Basquete', respostas_incorretas: ['Handebol', 'Vôlei', 'Futebol'] },
  { categoria: 'Esportes', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual esporte é disputado em quadra com raquetes e peteca?', resposta_correta: 'Badminton', respostas_incorretas: ['Tênis', 'Squash', 'Tênis de mesa'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte usa luvas e ringue?', resposta_correta: 'Boxe', respostas_incorretas: ['Judô', 'Taekwondo', 'Karatê'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte tem prova de maratona?', resposta_correta: 'Atletismo', respostas_incorretas: ['Natação', 'Ciclismo', 'Ginástica'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte é praticado com remo?', resposta_correta: 'Remo', respostas_incorretas: ['Canoagem', 'Surfe', 'Vela'] },
  { categoria: 'Esportes', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual esporte tem o termo home run?', resposta_correta: 'Beisebol', respostas_incorretas: ['Críquete', 'Rugby', 'Hóquei'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte é conhecido por slam dunk?', resposta_correta: 'Basquete', respostas_incorretas: ['Vôlei', 'Futebol', 'Handebol'] },
  { categoria: 'Esportes', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual esporte tem a prova de decatlo?', resposta_correta: 'Atletismo', respostas_incorretas: ['Natação', 'Ciclismo', 'Ginástica'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte é conhecido por tie-break?', resposta_correta: 'Tênis', respostas_incorretas: ['Vôlei', 'Basquete', 'Futebol'] },
  { categoria: 'Esportes', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual esporte utiliza pista oval e patins?', resposta_correta: 'Patinação de velocidade', respostas_incorretas: ['Hóquei', 'Surfe', 'Ciclismo'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte tem modalidades livre, costas, peito e borboleta?', resposta_correta: 'Natação', respostas_incorretas: ['Atletismo', 'Ciclismo', 'Remo'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte tem o termo grand slam?', resposta_correta: 'Tênis', respostas_incorretas: ['Golfe', 'Rugby', 'Vôlei'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte envolve lutas no tatame?', resposta_correta: 'Judô', respostas_incorretas: ['Boxe', 'Esgrima', 'Sumô'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte é conhecido como esporte da raquete e mesa?', resposta_correta: 'Tênis de mesa', respostas_incorretas: ['Badminton', 'Squash', 'Tênis'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte é praticado com arco e flecha?', resposta_correta: 'Tiro com arco', respostas_incorretas: ['Esgrima', 'Ginástica', 'Boxe'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte usa luvas e saco de pancadas nos treinos?', resposta_correta: 'Boxe', respostas_incorretas: ['Judô', 'Karatê', 'Taekwondo'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte é praticado em quadra com rede e bola?', resposta_correta: 'Vôlei', respostas_incorretas: ['Basquete', 'Futebol', 'Rugby'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte tem provas de 100 metros rasos?', resposta_correta: 'Atletismo', respostas_incorretas: ['Natação', 'Ciclismo', 'Remo'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte é conhecido como o esporte da bola laranja?', resposta_correta: 'Basquete', respostas_incorretas: ['Handebol', 'Vôlei', 'Futebol'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte é praticado com pranchas no mar?', resposta_correta: 'Surfe', respostas_incorretas: ['Remo', 'Vela', 'Canoagem'] },
  { categoria: 'Esportes', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual esporte tem disputa em quatro Grand Slams por ano?', resposta_correta: 'Tênis', respostas_incorretas: ['Golfe', 'Fórmula 1', 'Ciclismo'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte é conhecido como esporte do gelo?', resposta_correta: 'Hóquei no gelo', respostas_incorretas: ['Patinação artística', 'Curling', 'Esqui'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte usa tacadas em um campo com buracos?', resposta_correta: 'Golfe', respostas_incorretas: ['Beisebol', 'Críquete', 'Tiro ao alvo'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte é disputado em piscina?', resposta_correta: 'Natação', respostas_incorretas: ['Remo', 'Atletismo', 'Ciclismo'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte usa patins e música em apresentações?', resposta_correta: 'Patinação artística', respostas_incorretas: ['Hóquei', 'Esqui', 'Snowboard'] },
  { categoria: 'Esportes', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual esporte usa bastão e bola em campo?', resposta_correta: 'Hóquei de campo', respostas_incorretas: ['Beisebol', 'Críquete', 'Rugby'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte usa capacete, taco e patins no gelo?', resposta_correta: 'Hóquei no gelo', respostas_incorretas: ['Patinação', 'Curling', 'Esqui'] },
  { categoria: 'Esportes', dificuldade: 'facil', pontuacao: 10, pergunta: 'Qual esporte é praticado com bicicleta?', resposta_correta: 'Ciclismo', respostas_incorretas: ['Atletismo', 'Remo', 'Natação'] },
  { categoria: 'Esportes', dificuldade: 'medio', pontuacao: 20, pergunta: 'Qual esporte é conhecido pela expressão "par" e "birdie"?', resposta_correta: 'Golfe', respostas_incorretas: ['Tênis', 'Beisebol', 'Rugby'] },

  // Perguntas adicionais de Esportes - Difícil
  { categoria: 'Esportes', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual país ganhou a primeira Copa do Mundo de futebol feminino?', resposta_correta: 'Estados Unidos', respostas_incorretas: ['Alemanha', 'Brasil', 'Suécia'] },
  { categoria: 'Esportes', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o recorde mundial dos 100 metros rasos masculino?', resposta_correta: '9,58 segundos', respostas_incorretas: ['9,63 segundos', '9,69 segundos', '9,72 segundos'] },
  { categoria: 'Esportes', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Em que ano Michael Jordan se aposentou definitivamente?', resposta_correta: '2003', respostas_incorretas: ['2001', '2002', '2004'] },
  { categoria: 'Esportes', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual tenista tem mais títulos de Grand Slam masculino?', resposta_correta: 'Novak Djokovic', respostas_incorretas: ['Roger Federer', 'Rafael Nadal', 'Pete Sampras'] },
  { categoria: 'Esportes', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o nome do troféu da NBA?', resposta_correta: 'Larry O\'Brien Trophy', respostas_incorretas: ['Michael Jordan Trophy', 'Magic Johnson Trophy', 'Bill Russell Trophy'] },
  { categoria: 'Esportes', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual nadador tem mais medalhas olímpicas na história?', resposta_correta: 'Michael Phelps', respostas_incorretas: ['Mark Spitz', 'Katie Ledecky', 'Ian Thorpe'] },
  { categoria: 'Esportes', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Em que cidade foram realizados os primeiros Jogos Olímpicos modernos?', resposta_correta: 'Atenas', respostas_incorretas: ['Paris', 'Londres', 'Roma'] },
  { categoria: 'Esportes', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual é o recorde mundial da maratona masculina?', resposta_correta: '2:01:09', respostas_incorretas: ['2:02:57', '2:03:38', '2:04:26'] },
  { categoria: 'Esportes', dificuldade: 'dificil', pontuacao: 40, pergunta: 'Qual ginasta tem mais medalhas olímpicas individuais?', resposta_correta: 'Larisa Latynina', respostas_incorretas: ['Nadia Comaneci', 'Shannon Miller', 'Nastia Liukin'] },
];

async function seed() {
  const pool = new Pool({
    user: process.env.DB_USER,
    host: process.env.DB_HOST,
    database: process.env.DB_NAME,
    password: process.env.DB_PASSWORD,
    port: process.env.DB_PORT,
    ssl: process.env.DB_SSL === 'true' || process.env.NODE_ENV === 'production'
      ? { require: true, rejectUnauthorized: false }
      : false,
  });

  const force = process.env.SEED_FORCE === 'true';
  const countRes = await pool.query('SELECT COUNT(*)::int AS count FROM pergunta');
  const count = countRes.rows[0]?.count ?? 0;

  if (count > 0 && !force) {
    console.log(`Seed abortado: tabela pergunta ja possui ${count} registros.`);
    await pool.end();
    return;
  }

  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    if (force && count > 0) {
      await client.query('DELETE FROM pergunta');
    }
    for (const p of perguntas) {
      await client.query(
        'INSERT INTO pergunta (categoria, dificuldade, pontuacao, pergunta, resposta_correta, respostas_incorretas) VALUES ($1, $2, $3, $4, $5, $6)',
        [p.categoria, p.dificuldade, p.pontuacao, p.pergunta, p.resposta_correta, JSON.stringify(p.respostas_incorretas)]
      );
    }
    await client.query('COMMIT');
    console.log(`Seed concluido: ${perguntas.length} perguntas inseridas.`);
  } catch (error) {
    await client.query('ROLLBACK');
    console.error('Erro ao inserir perguntas:', error);
    process.exitCode = 1;
  } finally {
    client.release();
    await pool.end();
  }
}

seed();
